### ISSUE TITLE
Support httplug 2.0, etc

### ISSUE THREAD

**Issue by karptonite** [typesense/typesense-php#12]
## Description
I'm having trouble installing this package. it seems that some of the composer dependencies are too strict. Looking quickly at the code, I don't see why the dependency on httplug should be locked at version 1. I haven't looked into this in more detail, but there may be other similar dependencies that are over-specified in the composer.json file.

## Steps to reproduce

1. Start with a clean project with `composer init`.
2. run `composer require php-http/guzzle6-adapter`
3. run `composer require typesense/typesense-php`

## Expected Behavior
Package installs.

## Actual Behavior

```
  Problem 1
    - Root composer.json requires typesense/typesense-php ^4.4 -> satisfiable by typesense/typesense-php[v4.4.0].
    - typesense/typesense-php v4.4.0 requires php-http/httplug ^1.0 -> found php-http/httplug[v1.0.0, v1.1.0] but the package is fixed to 2.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

**Comment by jasonbosco** [comment]
Merged the #13, thank you!
