### ISSUE TITLE
Problem with Composer

### ISSUE THREAD

**Issue by waelsy** [typesense/typesense-php#18]
Hello,

i am facing a problem using php client with composer. The Autoloader is unable to load the files.
In composer.json, i have:

    "require": {
        "php": "^7.0",                      
        "guzzlehttp/guzzle": "~6.0",
        "php-http/curl-client": "^2.2",
        "typesense/typesense-php": "^2.0"                
    },  

after first composer install or update, it loads the typesense folder in vendor, till here everything is right.

in PHP :
require_once '../vendor/autoload.php'; // Autoload for composer-packages
use Typesense\Client;
$client = new Client(........................

this will through an error:
Fatal error: Uncaught Error: Class 'Typesense\Client' not found in .........................

i did not find any helpfull information on the internet.
when i looked at the files in typesense\typesense-php\src, e.g. Client.php
in the header it uses the name space  "Devloops\Typesence"

namespace Devloops\Typesence;
use Devloops\Typesence\Lib\Configuration;

Where this Devloops come from ?!

it tried also to execute:
composer dump-autoload -o
then i get an error that typesence Classes does not comply with psr-4 a utoloading standard. Skipping.

any idea how to make it work with php ?

Regards
Wael

**Comment by waelsy** [comment]
i noticed already typing error in the name of  Namespaces in the classes:
in the all files inside the src folders, the namespace include "Typesence" not "Typesense"
i hope it got fixed soon.
but for now i got make it work using the declaration:

use Devloops\Typesence\Client;

Regards
Wael

**Comment by jasonbosco** [comment]
Hi @waelsy it looks like you're using an old version of the php package, when it was still maintained by @AbdullahFaqeir as part of his company Devloops. We've since adopted his work as an official Typesense library, as of v4. Could you update to the latest version of the php package?

**Comment by waelsy** [comment]
@jasonbosco  you are write .. i did not notice the version number. 
Thank you.
