### ISSUE TITLE
Typesense\Aliases::offsetGet deprecated with PHP 8.1

### ISSUE THREAD

**Issue by piolet** [typesense/typesense-php#27]
## Description
Hi all,

I Upgrade Php 8.0 to 8.1, and i have now this warning

**Deprecated**:  Return type of Typesense\Aliases::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in **/.../vendor/typesense/typesense-php/src/Aliases.php** on line 100

## Metadata

**Typsense Version**: typesense/typesense:0.22.2

**OS**: Mac OS

**Comment by meetroger-machine-user** [comment]
Thank you!

**Comment by mkarnicki** [comment]
Thank you!
