### ISSUE TITLE
Couldn't use typesense client because of typo in folder's first letters case

### ISSUE THREAD

**Issue by Awais-cb** [typesense/typesense-php#31]
Hi 

hope you are doing well i got a problem configuring typesense in my project, when i tried to create typesense object it gave this error which seems like this

![Screenshot from 2022-12-09 16-19-31](https://user-images.githubusercontent.com/27766561/206691830-695b6f2f-00d5-4521-b1e5-4ce884e265c7.png)

but when i renamed this folder 

`/vendor/typesense/typesense-php/src/lib`

with L of lib folder in capital

`/vendor/typesense/typesense-php/src/Lib`

this solved the error but in production environment we cannot make changes to vendor folder is the anything that i am doing wrong? or is this any issue with this repo? please advise

here is my code for simply establishing the connection

```<?php
require_once(__DIR__ . '/vendor/autoload.php');
use Devloops\Typesence\Client;

try {
    $client = new Client(
        [
          'api_key'         => 'abcd',
          'nodes'           => [
            [
              'host'     => 'ip-address',
              'port'     => 'port',
              'protocol' => 'http',
            ],
          ],
          'connection_timeout_seconds' => 2,
        ]
    );
} catch (Exception $e) {
    echo $e->getMessage();
}```

**Comment by karakhanyans** [comment]
Hello @Awais-cb, could you please past here the OS that you are using and the version?

Thanks.

**Comment by Awais-cb** [comment]
Hi @karakhanyans I was using Ubuntu 20.04 and PHP version 7.3

but when i upgraded PHP to 7.4 issue was resolved so closing this issue Thanks for asking.
