### ISSUE TITLE
Composer: Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.

### ISSUE THREAD

**Issue by kdevan** [typesense/typesense-php#39]
## Description

Composer is displaying a warning that a package being used here is abandoned.

## Steps to reproduce

My composer configuration is set up like this:

```json
"config": {
    "optimize-autoloader": true,
    "preferred-install": "dist",
    "sort-packages": true,
    "allow-plugins": {
        "composer/package-versions-deprecated": true,
        "ergebnis/composer-normalize": true,
        "php-http/discovery": false
    },
    "github-protocols": ["https"]
}
```

Maybe the `composer/package-versions-deprecated` is showing this.

## Expected Behavior

No warning.

## Actual Behavior

`Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.`

## Metadata

**Typesense Version**: `0.24.1`

**Comment by Sammyjo20** [comment]
I'm having this issue as well - any chance this dependency could be updated?

**Comment by karakhanyans** [comment]
Hi @kdevan @Sammyjo20  

The issue was solved with this PR: https://github.com/typesense/typesense-php/releases/tag/v4.9.0

Please update to the latest version.
