### ISSUE TITLE
Version 4.8.4 uses union types which are not supported in php 7.4

### ISSUE THREAD

**Issue by cerven** [typesense/typesense-php#41]
## Description

Version 4.8.4 uses union return types in new class Presets which are not supported in php 7.4

## Steps to reproduce

Install 4.8.4 with php 7.4

## Expected Behavior

remove usage of union types or remove support for php 7.4 for this version

**Comment by karakhanyans** [comment]
@cerven the issue fixed in this PR and was released to the latest version: https://github.com/typesense/typesense-php/pull/42
