### ISSUE TITLE
PHP8.2 Deprecated Functionality: Creation of dynamic property Typesense\Analytics::$rules

### ISSUE THREAD

**Issue by pawel-detka** [typesense/typesense-php#45]
## Description

Running the client under PHP8.2 and using the Analytics I have an error:
`Deprecated Functionality: Creation of dynamic property Typesense\Analytics::$rules is deprecated in vendor/typesense/typesense-php/src/Analytics.php on line 19`

## Steps to reproduce

Run the client in the application
`$this->client->getAnalytics()->rules()->upsert($ruleName, $ruleConfiguration);`

## Expected Behavior
Add the private variable to the class 
`private AnalyticsRules $rules;`

## Actual Behavior
Warning message

## Metadata

**Typesense Version**:
0.25.1.rc3

**OS**:
MacOS 13.5.1
PHP 8.2.9

**Comment by karakhanyans** [comment]
Closing as issue was fixed.
