### ISSUE TITLE
Support psr/http-message version 2

### ISSUE THREAD

**Issue by kevinquillen** [typesense/typesense-php#48]
## Description

Currently cannot require this package to applications using psr/http-message higher than 1.0:

`typesense/typesense-php[v4.8.0, ..., v4.8.7] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.` Please expand the version constraint to allow it to be installed on systems that have http-message 2+.

## Metadata

**Typesense Version**: latest

**OS**: Linux

**Comment by karakhanyans** [comment]
Hi @kevinquillen 

The issue was solved with this PR: https://github.com/typesense/typesense-php/releases/tag/v4.9.0

Please update to the latest version.
