### ISSUE TITLE
Add schema cloning to the client

### ISSUE THREAD

**Issue by binarystarr** [typesense/typesense-php#54]
## Description

To help support a workflow that uses aliased collections, it would be great to be able to clone a schema when creating a new collection as referenced in the [typesense API docs](https://typesense.org/docs/0.25.2/api/collections.html#cloning-a-collection-schema). 

This would enable a more simplistic workflow that clones an existing schema before uploading documents to it and updating the alias to point to the new collection.

When this issue was raised on the community-help slack channel, Jason Bosco added the following:

Looks like we don't support it yet in the PHP client.
We'd need to accept GET parameters [here](https://github.com/typesense/typesense-php/blob/f91fd292ee587609972e9587d4392df0e423fa6b/src/Collections.php#L63) and then pass it down to the POST API call, to support collection cloning

**Comment by jasonbosco** [comment]
Resolved in #68
