### ISSUE TITLE
Installation not possible in Php projects with Monolog 1.x or Monolog 2 < 2.1 (released in May 2020)

### ISSUE THREAD

**Issue by MantraMedia** [typesense/typesense-php#7]
## Description

Impossible to install on older php projects

## Steps to reproduce

Create a php project that uses Monolog 1.x, 2.0x

## Expected Behavior

That typsense-php installs

## Actual Behavior

Installation is not possible as Monolog V2.1+ is required which was released in May 2020

I just see simple log usage, please allow Monolog ^1.0+ as a requirement

**Comment by jasonbosco** [comment]
@MantraMedia I just addressed this in 3453ef0. Will publish a new release shortly.

**Comment by jasonbosco** [comment]
Published v4.2.1 with this update.
