### ISSUE TITLE
URL malformed

### ISSUE THREAD

**Issue by georgeboot** [typesense/typesense-php#73]
## Description

After we deployed (using kubernetes)  Laravel Scout with Typesense (upgrading from Meilisearch) the packges incorrectly formats the url.

We set an env called `TYPESENSE_HOST` to `typesense.default.svc.cluster.local` (the service hostname inside our cluster) but we get a Guzzle exception with curl error code 3 (malformed url) stating:
`
cURL error 3: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://typesense.default.svc.cluster.local:tcp//10.43.114.99:8108/collections/datasets
`

`10.43.114.99` is indeed the IP behind the service hostname, but it is never entered. Same for the `tcp`.

## Metadata

**Typesense Version**: 4.9.3 with server 26.0

**OS**: ubuntu

## Config
```php
// config/scout.php

    'typesense' => [
        'client-settings' => [
            'api_key' => env('TYPESENSE_API_KEY', 'xyz'),
            'nodes' => [
                [
                    'host' => env('TYPESENSE_HOST', 'localhost'),
                    'port' => env('TYPESENSE_PORT', '8108'),
                    'path' => env('TYPESENSE_PATH', ''),
                    'protocol' => env('TYPESENSE_PROTOCOL', 'http'),
                ],
            ],
            'connection_timeout_seconds' => env('TYPESENSE_CONNECTION_TIMEOUT_SECONDS', 2),
            'healthcheck_interval_seconds' => env('TYPESENSE_HEALTHCHECK_INTERVAL_SECONDS', 30),
            'num_retries' => env('TYPESENSE_NUM_RETRIES', 3),
            'retry_interval_seconds' => env('TYPESENSE_RETRY_INTERVAL_SECONDS', 1),
        ],
        'model-settings' => [], // etc.
```

environment valriables set:
```yaml
TYPESENSE_HOST: "typesense.default.svc.cluster.local"
TYPESENSE_API_KEY: "xyz"
```

**Comment by georgeboot** [comment]
Turns out this was a kubernetes issue. I still have no clue why curl decided to malform the url, but it now works. Closing.

**Comment by nimah79** [comment]
Hello!
I have the same problem.
