### ISSUE TITLE
Can't compile composer on PHP version 7.2.24

### ISSUE THREAD

**Issue by onassar** [typesense/typesense-php#8]
## Description
Can't compose for 7.2.24 (ignore 7.3.11 warning; that's my Mac; my VM runs 7.2.24)

## Steps to reproduce
Run composer:
https://i.imgur.com/eNggRDL.png

## Expected Behavior
Composed would run normally

## Actual Behavior
Can't compose

**Typsense Version**:
`4.2.0`

**OS**:
macOS / Linux VM

**Comment by MantraMedia** [comment]
This project is using typed properties which require PHP 7.4+

**Comment by onassar** [comment]
Any idea which parts specifically? I could amend it so it's useful for 7.2+

**Comment by MantraMedia** [comment]
Pretty much all of it and be aware that PHP 7.2 is EOL since Nov 30.

**Comment by onassar** [comment]
Gotcha thanks
