### ISSUE TITLE
Http\Discovery\NotFoundException after upgrade to 4.3

### ISSUE THREAD

**Issue by victorbosh** [typesense/typesense-php#9]
Http\Discovery\NotFoundException
No HTTPlug clients found. Make sure to install a package providing "php-http/client-implementation". Example: "php-http/guzzle6-adapter".

I see you do use Symfony\Component\HttpClient\HttplugClient; in your examples and 'client' => new HttplugClient(), but there is no such thing as Symfony\Component\HttpClient\HttplugClient

**Comment by jasonbosco** [comment]
@babeuloula any thoughts on this?

**Comment by babeuloula** [comment]
@victorbi Hi, can you tell me what kind of HTTP client you use ?

**Comment by victorbosh** [comment]
I installed symfony/http-client and it works now, maybe you should add it in 'require', instead of 'require-dev'

**Comment by babeuloula** [comment]
@victorbosh Nop, HTTPlug provide adapters and let the user the ability to use Guzzle, Symfony Client or any other http client.

**Comment by babeuloula** [comment]
@victorbosh You can can read this section : https://github.com/typesense/typesense-php#usage

> Typesense use HTTPlug. List of clients & adapters here

And read this link : http://docs.php-http.org/en/latest/clients.html

**Comment by victorbosh** [comment]
I did. Anyway it is ok now, Thanks
